---
- hosts: webservers
  become: true
  tasks:
    - name: Install Apache2 on Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: Start and enable Apache2 service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
        mode: '0644'
